// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtLMaWhrlpdtiD_1ZcrfWq_VC8APklKs8',
    appId: '1:976788969184:web:7014c3c3d9c417bf9e2285',
    messagingSenderId: '976788969184',
    projectId: 'stravamoto-42daa',
    authDomain: 'stravamoto-42daa.firebaseapp.com',
    storageBucket: 'stravamoto-42daa.firebasestorage.app',
    measurementId: 'G-2KYN01ZRR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsihzFgOydf8D72WYv8SqEHCGbzy_7GLI',
    appId: '1:976788969184:android:12b1a10a1e1b44a29e2285',
    messagingSenderId: '976788969184',
    projectId: 'stravamoto-42daa',
    storageBucket: 'stravamoto-42daa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS4JYKH5Jyt7GC9ri8knteUqK37Jvm53k',
    appId: '1:976788969184:ios:05ce1f82c43d1c579e2285',
    messagingSenderId: '976788969184',
    projectId: 'stravamoto-42daa',
    storageBucket: 'stravamoto-42daa.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS4JYKH5Jyt7GC9ri8knteUqK37Jvm53k',
    appId: '1:976788969184:ios:05ce1f82c43d1c579e2285',
    messagingSenderId: '976788969184',
    projectId: 'stravamoto-42daa',
    storageBucket: 'stravamoto-42daa.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
